spring.application.name=task-tracker-api

jwt.secret=${JWT_SECRET:mySuperSecretKey123-asfjklas21sjflasflj}
jwt.expiration=86400000

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

app.admin.email=${ADMIN_EMAIL:admin@test.com}
app.admin.password=${ADMIN_PASSWORD:adminPassword1}